### ISSUE TITLE
Blocking Users

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#12]
Blocking users you don't like/have personal issues with, the same thing as on every social network.
- X's Profile not visible for user Y
- X's Questions and answers not visible for user Y
- Y's Profile not visible for user X
- Y's Questions and answers not visible for user X

This will cause that these 2 users, except if they end up making new accounts (for stalking), being practically invisible for each other, blocking one user basically shows you have either personal or any issues with them and don't want to interact with them in any way.

**Comment by ghost** [comment]
Suggestion  

Blocking doesn't need to be two-way, especially since all content is public. The most useful "block" would simply hide the blocked user:  
X blocks Y means
- X does not see Y's questions anywhere
- X does not see Y's answers anywhere
- X does not see Y's profile anywhere except X's blocked user list
- Y's experience of the site is unaffected

**Comment by raccube** [comment]
We can also block the IPs of anonymous users.

Do not display a list of them but provide a way for users to clear their blocked anons.

**Comment by raccube** [comment]
Affected functionality:

- following users
- asking questions
- answering questions
- commenting on answers
- smiling comments/answers
- adding users to lists
