### ISSUE TITLE
Syncronize Canny and GitHub Issues

### ISSUE THREAD

**Issue by rugk** [Retrospring/retrospring#1222]
### Pitch

Could not you somehow use web hooks on both sides or so to syncronize Canny bugs/feature requests to GitUub and vice versa?

### Motivation

This would be useful, because I was confused where to report stuff now and I would have to search two issue trackers to find out whether something was already reported etc.
Two places are just harder to work with than a single source of truth.

**Comment by pixeldesu** [comment]
I don't think it's technically viable to do this.

Having two feature/bug trackers might sound a bit counter-productive, but in this case it's a bit more about user experience.

Canny exists for users that don't have a GitHub account, giving them easier access to report bugs and request features. Since "regular users" have a lot of different ideas, it's also a good way for us to gather feedback from more users (with the votes) and once we plan to add a feature or confirm a bug, we usually create a fitting issue on GitHub.

Since a lot of people request/report the same things, I need to merge stuff in Canny, if all of those requests created issues, our GitHub Issues would be full with duplicates.

If you have a GitHub account, you can, if you want to, directly create issues here. Here you might have a more technical discussion with us, and on Canny other users might chip in and approve/comment on your feature idea.

In the end, we see all of the requests, and some issue or another will land in GitHub anyway, but manually is fine at the moment!

_Also, I don't know how I forgot to reply to this before, but the past months have been kinda busy/stressful. But I hope the answer suffices!_

**Comment by rugk** [comment]
Thanks a lot for the detailed answer, that does indeed explain a lot and was apparently not clear to me!
