### ISSUE TITLE
"Manage list memberships" undocumented / inconsistent

### ISSUE THREAD

**Issue by coderobe** [Retrospring/retrospring#130]
There's a button labelled "Manage list memberships" in the navbar - this only appears on profile pages, but not on your own profile page.
![image](https://user-images.githubusercontent.com/8442384/83341335-88398100-a2e2-11ea-9360-b53ecae22a39.png)

Perhaps this button should be present all the time or something, as-is it appears a bit out of place with it appearing/disappearing out of the navbar without notice.

![image](https://user-images.githubusercontent.com/8442384/83341368-eebe9f00-a2e2-11ea-81f5-17703dd6a447.png)
There's also not much information when clicking this button, A quick documentation text when no lists exist would be v useful.

**Comment by pixeldesu** [comment]
I'll close this, because this was implemented and I forgot to check the issue. The new tabbed sub-navigation in the home timeline has an explainer on the lists feature in it, if no lists were created.

![image](https://user-images.githubusercontent.com/1774242/212444191-f97d3cd5-e22a-4aa0-8b6d-f523b64fe996.png)
