### ISSUE TITLE
When you smile, it turns into a frown, and that feels weird

### ISSUE THREAD

**Issue by faho** [Retrospring/retrospring#181]
When you click the smile button, the previous happy smiley turns into a frown to show that you've already done that, and if you clicked it again it would un-smile.

That feels a bit weird - I've clicked something to show I'm happy about it, and now it shows me a symbol of unhappiness?

Screenshots to show what I mean:

A post that I liked, showing a frown:

![Screenshot_20210805_183615](https://user-images.githubusercontent.com/5185367/128387924-2378009d-3010-4df4-83a7-287f9d2adc79.png)

A post that I didn't like, showing a smiley:

![Screenshot_20210805_183630](https://user-images.githubusercontent.com/5185367/128387941-8242e2d9-b3d0-406d-8d03-4fac60847bec.png)

(to be clear I didn't click the button to show I liked it, I did like it in principle)

**Comment by raccube** [comment]
Could make it not change to a frown. However, I think we'd need some kind of obvious feedback for a successful 'smile'. Otherwise it would be easy to mistake the button turning green (or whatever your success colour is) as being the focus state. Maybe animate it or show a toast? 

@nilsding @pixeldesu thoughts?

**Comment by raccube** [comment]
I'd prefer switching to a heart or star icon (and renaming to likes or favourites) which we could switch between a filled and outlined state. Although the reason we stuck to smiles because they're not horrendously generic.

**Comment by pixeldesu** [comment]
> Although the reason we stuck to smiles because they're not horrendously generic.

The reason is because it was called "Smiles" on Formspring before as well.

And my general stance on it is...understanding I guess. The main idea was that it basically directly showed the action you are about to do, without having to interact with the button in any way, simply because there isn't much of an "intermediate" smile state. Having a :| face also looks "negative" rather than "neutral".

It's a bit of a tough UI/UX problem, of which I have no general idea how to fix it. Maybe only show the frown on hover? But that basically caps it to everything that is a non-touch device.

_But due to the methodology and meaning of smiles to the platform, I strongly oppose renaming it to favorites/likes._

**Comment by carlydotwebsite** [comment]
A couple potential ways to implement it:
- change from line-smiley to solid (`fa-smile-o` to `fa-smile`, or `far fa-smile` to `fas fa-smile` in FA parlance)
- keep the line-style smiley, but have it initially grey and change to a color when "smiled"

Probably you could easily add animation to either. The former was probably how I was going to do it for myself using a userscript, admittedly, but I don't personally feel strongly about one or the other being a better solution, as long as it's clear which is the "on" state and which is the "off" state.

**Comment by raccube** [comment]
Related: https://retrospring.net/@retrospring/a/108716226174068915
