### ISSUE TITLE
Profile page answers and question pages may get mixed up

### ISSUE THREAD

**Issue by fizzyarthur** [Retrospring/retrospring#313]
Description:

The additional content that is loaded with the "load more" button may also load on a question page (the one which shows answers to a question).

Steps to reproduce:

Go to your profile page > scoll until the "load more" button appears > quickly touch the "_n_ answers" button and the "load more" button.

Expected behaviour:

The question page should not load answers from different questions.

Observations:

This issue doesn't happen if you try to reproduce it from the main timeline, it's specific to the profile page.

Test setup:

Samsung galaxy A8 2018 (Android 9)
Bromite 96.0

Screenshots:

| ![Screenshot_20220117-182929_Bromite](https://user-images.githubusercontent.com/96353632/149841715-670eeb4c-4913-42e4-b69c-603b1d3137ad.jpg) | ![Screenshot_20220117-183105_Bromite](https://user-images.githubusercontent.com/96353632/149841743-053aee52-8357-41cf-983e-577feb82be34.jpg) |
| - | - |

**Comment by nilsding** [comment]
That's an interesting bug, thanks for reporting.

From what I can tell this happens because the HTTP request that is made when clicking the _Load more_ button does not get cancelled on a new page load. When that request completes its response is be appended to the `#timeline` or `#answers` div, depending on whether you're in the main timeline or an answers page (including the user profile).

I think it's theoretically possible to encounter this going from an answer page to a user profile, but in practice this very rarely happens due to profile pages being a bit more complex.

**Comment by pixeldesu** [comment]
I might be able to address this issue once I rework the frontend pagination logic, when I'm porting it away from CoffeeScript.

**Comment by pixeldesu** [comment]
I think with the Turbo Streams pagination I decreased the likelyhood of this happening quite a lot, this should be fine now.
