### ISSUE TITLE
Uploading an image with the same filename doesn't crop it.

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#511]
**Steps to reproduce:**

1. Set your profile picture. Do not crop it.
2. Try uploading it again, this time adjust the cropping. After submitting, the cropping will not change.

**Work around**

1. Upload a different picture.
2. Upload the picture you want again
3. Crop adjustment should work as expected.

**Comment by pixeldesu** [comment]
Something we should probably do in general with uploaded files that might fix this: We should either hash the name entirely (so the origin filename is not preserved), or at least prepend a timestamp to the name, so every upload is unique.

**Comment by nilsding** [comment]
I don't think the file name is the problem here, cropping works just fine if you select a crop area (tried this with some kind of S3 storage and local storage).

what I noticed locally is that for some reason the cropper doesn't get initialised properly, it should select the entire picture:

<img width="484" alt="Screenshot 2023-06-16 at 20 14 14" src="https://github.com/Retrospring/retrospring/assets/1809170/710acd02-2424-4cf2-87d1-6aff0b261cc2">

**Comment by pixeldesu** [comment]
This was fixed in [2023.0901.0](https://github.com/Retrospring/retrospring/releases/tag/2023.0901.0)
