### ISSUE TITLE
Twitter Authorization Scope

### ISSUE THREAD

**Issue by Larke12** [Retrospring/retrospring#629]
When connecting to Twitter a list of abilities for the requested scope are shown:

![image](https://user-images.githubusercontent.com/6708276/185204771-08632ac2-8f53-449a-8922-9a2225241eee.png)

Would it be possible to limit the access required? Or are all/some of these required to be able to operate as intended? At the moment, it looks like the primary operation only requires posting tweets to the account.

**Comment by nilsding** [comment]
Hi, this is because we are still using APIv1 which only has three scopes: read, write (which is what it's set to), and write including direct messages.  
While APIv2 has some more granular scopes, we haven't really gotten around to migrate to it, especially since it requires developers apply for it (perhaps even pay for it, I don't know), and the current OAuth application is still bound to my private Twitter account that I haven't touched in years.

That being said, it is definitely something that will be looked into the future.  [We get asked](https://twitter.com/Retrospring/status/1473345966052941829) [about this](https://twitter.com/Retrospring/status/1475528967130132487) [quite a lot](https://twitter.com/Retrospring/status/1551430997023023105).

@raccube @pixeldesu one idea that I just got: maybe we can create a completely new OAuth app on Twitter that's not bound to any personal account, and only create new connections using it?  I think the current services set-up works fine here: the `Services::Twitter` service could then be renamed to e.g. `Services::TwitterLegacy` and co-exist with the one that uses the new OAuth app.  Should we need to vendor a gem because e.g. some class names overlap we can try out [Automatiek](https://github.com/segiddins/automatiek) (also used by Bundler).

**Comment by pixeldesu** [comment]
Good thing we didn't invest any time into this.

Twitter is killing free API access in a week, so we're focusing on #1041 instead.
