### ISSUE TITLE
API

### ISSUE THREAD

**Issue by neptuwunium** [Retrospring/retrospring#8]
To make everyone's life easier all feature requests are staggered until the API is complete and functioning. All future feature implementations must also provide appropiate API endpoints or adjustments.
- [x] Application Creation
- [x] Application Auth
- [x] Application Metrics
- [x] User API
- [x] Comments
- [x] Questions
- [x] Answers
- [x] Smiles
- [x] Reports
- [x] Moderation
- [x] Inbox
- [x] Notifications
- [x] Subscriptions
- [x] Groups
- [x] Utilities
- [x] Settings
- [ ] Documentation
  - [ ] User
  - [ ] Questions
  - [ ] Answers
  - [ ] Reports
  - [ ] Moderation
  - [ ] Group
  - [ ] Setting
  - [ ] Utility
- [x] Tests
  - [x] User
  - [x] Questions
  - [x] Answers
  - [x] Reports
  - [x] Moderation
  - [x] Group
  - [x] Setting
  - [x] Utility

Original report at retrospring/bugs#9

**Comment by pixeldesu** [comment]
I'm going to close this issue. We still want an API obviously, but this has been a tracking issue for the old API.

We are working towards having reusable implementations for all site features with the [use case/interactor pattern](https://github.com/orgs/Retrospring/projects/3?query=is%3Aopen+sort%3Aupdated-desc), and once all of those are added, we can refocus our plans for an API and start to implement it step-by-step. Trying to introduce a feature-complete API last time (tracked here) broke our back.

Anyway, the code still exists in the https://github.com/Retrospring/retrospring/tree/api branch for preservation purposes (since all that work went into it).
