### ISSUE TITLE
Refactor inbox show action

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#965]
Probably one of the largest actions in Retrospring, the code of it is massive AND complicated at that.

It might be worth introducing some DTO logic for filtering here, so that is handled elsewhere and not right in the controller.

Another thing to get rid of is the massive amount of globals used here.

With the refactoring it of course would be nice to directly solve the issue present in #959 as well.

**Comment by nilsding** [comment]
`s/globals/ivars/` I guess, but I agree, it's one of the messiest controllers we have.

was about to say "at least we have tests", but it's literally just expecting to render the correct template. 😑 

one idea I have is to split up the controller a bit too, something like:

```
/inbox         => inbox#index
/inbox/:author => inbox#show
```

(fun fact: we already have a `/inbox/:author` route, it's just not in use since the current front-end form just ends up doing a `GET /inbox?author=whatever` ... guess we can either redirect that, fix it in JS, or both) 🤯
